export enum ERROR_CODE {
    USER_NOT_CREATED = "USER_NOT_CREATED",
    INVALID_GRANT = "invalid_grant",
    NO_TOKEN = "NO_TOKEN",
    INVALID_TOKEN = "INVALID_TOKEN",
    UNKNOWN = "UNKNOWN",
    TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",
}