import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";
import { syncColumns } from "./base";

export const shipmentsTable = sqliteTable("shipments", {
  shipmentID: integer().primaryKey({ autoIncrement: true }),
  companyID: text().notNull(),
  waybill: text(),
  serviceType: integer(),
  serviceTypeName: text(),
  packageType: integer(),
  readyDate: text(),
  dueDate: text(),
  codType: text(),
  codAmount: real(),
  sender: text(),
  senderName: text(),
  senderAddressLine1: text(),
  senderAddressLine2: text(),
  senderZip: text(),
  senderPhoneNumber: text(),
  senderContactPerson: text(),
  orderNotes: text(),
  consigneeNum: text(),
  consigneeName: text(),
  addressLine1: text(),
  addressLine2: text(),
  zip: text(),
  phoneNumber: text(),
  contactPerson: text(),
  createdUserID: integer(),
  createdDate: text(),
  lastTransferDate: text(),
  status: text().notNull(),
  qty: integer(),
  items: text(),
  templateID: integer(),
  manifestDL: text(),
  assignPK: integer(),
  assignDL: integer(),
  division: text(),
  lastEventComment: text(),
  reason: text(),
  barcode: text(),
  referenceNo: text(),
  manifestPk: text(),
  manifest: text().notNull(),
  latitude: real(),
  longitude: real(),
  city: text(),
  photoOnEvent: integer({ mode: "boolean" }),
  photoOnDelivery: integer({ mode: "boolean" }),

  ...syncColumns,
});


export type TShipmentsData = typeof shipmentsTable.$inferSelect;
